// Generated by CoffeeScript 1.10.0
(function() {
  var Controller, Model, View, controller, model, view;

  Model = (function() {
    function Model() {}

    Model.prototype.board = [1, 2, 3, 4, 5, 6, 7, 8, 9];

    Model.prototype.turn = 1;

    Model.prototype.win = false;

    Model.prototype.winner = '';

    Model.prototype.win_coord = [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]];

    return Model;

  })();

  Controller = (function() {
    function Controller(model1, view1) {
      this.model = model1;
      this.view = view1;
    }

    Controller.prototype.round = function() {
      return this.view.draw_board(this.model.board);
    };

    return Controller;

  })();

  View = (function() {
    function View() {}

    View.prototype.draw_board = function(board) {
      var i, j, results;
      document.write('--------' + "<br>");
      results = [];
      for (i = j = 0; j < 3; i = ++j) {
        document.write('|', board[0] + i * 3, '|', board[1] + i * 3, '|', board[2] + i * 3, '|', "<br>");
        results.push(document.write('--------' + "<br>"));
      }
      return results;
    };

    return View;

  })();

  model = new Model();

  view = new View();

  controller = new Controller(model, view);

  controller.round();

}).call(this);
